[2025-07-24T18:55:50.958+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_full_etl_dag.Run_data_quality_checks manual__2025-07-24T18:40:08.391579+00:00 [queued]>
[2025-07-24T18:55:50.968+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_full_etl_dag.Run_data_quality_checks manual__2025-07-24T18:40:08.391579+00:00 [queued]>
[2025-07-24T18:55:50.969+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T18:55:50.988+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): Run_data_quality_checks> on 2025-07-24 18:40:08.391579+00:00
[2025-07-24T18:55:50.997+0000] {standard_task_runner.py:60} INFO - Started process 2274 to run task
[2025-07-24T18:55:51.003+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tunestream_full_etl_dag', 'Run_data_quality_checks', 'manual__2025-07-24T18:40:08.391579+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/step12345.py', '--cfg-path', '/tmp/tmprl7ptyx0']
[2025-07-24T18:55:51.006+0000] {standard_task_runner.py:88} INFO - Job 126: Subtask Run_data_quality_checks
[2025-07-24T18:55:51.075+0000] {task_command.py:423} INFO - Running <TaskInstance: tunestream_full_etl_dag.Run_data_quality_checks manual__2025-07-24T18:40:08.391579+00:00 [running]> on host 737498b59352
[2025-07-24T18:55:51.149+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tunestream_full_etl_dag' AIRFLOW_CTX_TASK_ID='Run_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T18:40:08.391579+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T18:40:08.391579+00:00'
[2025-07-24T18:55:51.151+0000] {logging_mixin.py:188} INFO - check: SELECT COUNT(*) FROM users WHERE userid IS NULL
[2025-07-24T18:55:51.160+0000] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2025-07-24T18:55:51.164+0000] {sql.py:450} INFO - Running statement: SELECT COUNT(*) FROM users WHERE userid IS NULL, parameters: None
[2025-07-24T18:55:51.166+0000] {sql.py:459} INFO - Rows affected: 1
[2025-07-24T18:55:51.167+0000] {logging_mixin.py:188} INFO - check: SELECT COUNT(*) FROM songs WHERE song_id IS NULL
[2025-07-24T18:55:51.173+0000] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2025-07-24T18:55:51.177+0000] {sql.py:450} INFO - Running statement: SELECT COUNT(*) FROM songs WHERE song_id IS NULL, parameters: None
[2025-07-24T18:55:51.179+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/step12345.py", line 259, in Run_data_quality_checks
    records = postgres_hook.get_records(sql)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 261, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "song_id" does not exist
LINE 1: SELECT COUNT(*) FROM songs WHERE song_id IS NULL
                                         ^
HINT:  Perhaps you meant to reference the column "songs.songid".

[2025-07-24T18:55:51.196+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_full_etl_dag, task_id=Run_data_quality_checks, execution_date=20250724T184008, start_date=20250724T185550, end_date=20250724T185551
[2025-07-24T18:55:51.211+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 126 for task Run_data_quality_checks (column "song_id" does not exist
LINE 1: SELECT COUNT(*) FROM songs WHERE song_id IS NULL
                                         ^
HINT:  Perhaps you meant to reference the column "songs.songid".
; 2274)
[2025-07-24T18:55:51.260+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T18:55:51.284+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
