[2025-07-24T18:47:48.443+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_full_etl_dag.Load_time_dim_table manual__2025-07-24T18:46:57.904001+00:00 [queued]>
[2025-07-24T18:47:48.689+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_full_etl_dag.Load_time_dim_table manual__2025-07-24T18:46:57.904001+00:00 [queued]>
[2025-07-24T18:47:48.739+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T18:47:48.937+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): Load_time_dim_table> on 2025-07-24 18:46:57.904001+00:00
[2025-07-24T18:47:49.206+0000] {standard_task_runner.py:60} INFO - Started process 2123 to run task
[2025-07-24T18:47:49.292+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tunestream_full_etl_dag', 'Load_time_dim_table', 'manual__2025-07-24T18:46:57.904001+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/step12345.py', '--cfg-path', '/tmp/tmpclcv_q8j']
[2025-07-24T18:47:49.363+0000] {standard_task_runner.py:88} INFO - Job 113: Subtask Load_time_dim_table
[2025-07-24T18:47:51.089+0000] {task_command.py:423} INFO - Running <TaskInstance: tunestream_full_etl_dag.Load_time_dim_table manual__2025-07-24T18:46:57.904001+00:00 [running]> on host 737498b59352
[2025-07-24T18:47:51.554+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tunestream_full_etl_dag' AIRFLOW_CTX_TASK_ID='Load_time_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T18:46:57.904001+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T18:46:57.904001+00:00'
[2025-07-24T18:47:51.557+0000] {logging_mixin.py:188} INFO - Executing transformation for table: time
[2025-07-24T18:47:51.652+0000] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2025-07-24T18:47:51.715+0000] {sql.py:450} INFO - Running statement: TRUNCATE TABLE time; INSERT INTO time 
        SELECT start_time, extract(hour from start_time), extract(day from start_time), extract(week from start_time),
               extract(month from start_time), extract(year from start_time), extract(DOW from start_time)
        FROM songplays
    , parameters: None
[2025-07-24T18:47:51.807+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/step12345.py", line 232, in load_time_dim_task
    load_table("postgres_local", "time", SqlQueries.time_table_insert)
  File "/opt/airflow/dags/step12345.py", line 177, in load_table
    postgres_hook.run(sql_formatted)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "time_pkey"
DETAIL:  Key (start_time)=(2018-11-14 04:53:36) already exists.

[2025-07-24T18:47:51.902+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_full_etl_dag, task_id=Load_time_dim_table, execution_date=20250724T184657, start_date=20250724T184748, end_date=20250724T184751
[2025-07-24T18:47:52.088+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 113 for task Load_time_dim_table (duplicate key value violates unique constraint "time_pkey"
DETAIL:  Key (start_time)=(2018-11-14 04:53:36) already exists.
; 2123)
[2025-07-24T18:47:52.424+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T18:47:52.712+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
