[2025-07-24T18:04:24.305+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_full_etl_dag.stage_events manual__2025-07-24T18:04:15.387612+00:00 [queued]>
[2025-07-24T18:04:24.368+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_full_etl_dag.stage_events manual__2025-07-24T18:04:15.387612+00:00 [queued]>
[2025-07-24T18:04:24.399+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T18:04:24.555+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): stage_events> on 2025-07-24 18:04:15.387612+00:00
[2025-07-24T18:04:24.604+0000] {standard_task_runner.py:60} INFO - Started process 1346 to run task
[2025-07-24T18:04:24.654+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tunestream_full_etl_dag', 'stage_events', 'manual__2025-07-24T18:04:15.387612+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/step12345.py', '--cfg-path', '/tmp/tmpdao4vpt4']
[2025-07-24T18:04:24.738+0000] {standard_task_runner.py:88} INFO - Job 72: Subtask stage_events
[2025-07-24T18:04:25.313+0000] {task_command.py:423} INFO - Running <TaskInstance: tunestream_full_etl_dag.stage_events manual__2025-07-24T18:04:15.387612+00:00 [running]> on host 737498b59352
[2025-07-24T18:04:25.704+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tunestream_full_etl_dag' AIRFLOW_CTX_TASK_ID='stage_events' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T18:04:15.387612+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T18:04:15.387612+00:00'
[2025-07-24T18:04:25.782+0000] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2025-07-24T18:04:25.969+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/step12345.py", line 86, in json_to_sql
    data = json.load(f)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 284)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/step12345.py", line 150, in stage_events_task
    json_to_sql("postgres_local","staging_events",LOG_DATA_PATH,event_columns)
  File "/opt/airflow/dags/step12345.py", line 96, in json_to_sql
    cur.execute(sql_insert, values)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: ""
LINE 1: ...PUT', 'Login', NULL, 52, NULL, 307, 1541207073796, NULL, '')
                                                                    ^

[2025-07-24T18:04:26.055+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_full_etl_dag, task_id=stage_events, execution_date=20250724T180415, start_date=20250724T180424, end_date=20250724T180426
[2025-07-24T18:04:26.130+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 72 for task stage_events (invalid input syntax for type integer: ""
LINE 1: ...PUT', 'Login', NULL, 52, NULL, 307, 1541207073796, NULL, '')
                                                                    ^
; 1346)
[2025-07-24T18:04:26.161+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T18:04:26.233+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
