[2025-07-24T18:50:45.131+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_full_etl_dag.Load_time_dim_table manual__2025-07-24T18:40:08.391579+00:00 [queued]>
[2025-07-24T18:50:45.142+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_full_etl_dag.Load_time_dim_table manual__2025-07-24T18:40:08.391579+00:00 [queued]>
[2025-07-24T18:50:45.143+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2025-07-24T18:50:45.154+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): Load_time_dim_table> on 2025-07-24 18:40:08.391579+00:00
[2025-07-24T18:50:45.161+0000] {standard_task_runner.py:60} INFO - Started process 2166 to run task
[2025-07-24T18:50:45.169+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tunestream_full_etl_dag', 'Load_time_dim_table', 'manual__2025-07-24T18:40:08.391579+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/step12345.py', '--cfg-path', '/tmp/tmpmwyx4q89']
[2025-07-24T18:50:45.177+0000] {standard_task_runner.py:88} INFO - Job 115: Subtask Load_time_dim_table
[2025-07-24T18:50:45.228+0000] {task_command.py:423} INFO - Running <TaskInstance: tunestream_full_etl_dag.Load_time_dim_table manual__2025-07-24T18:40:08.391579+00:00 [running]> on host 737498b59352
[2025-07-24T18:50:45.300+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tunestream_full_etl_dag' AIRFLOW_CTX_TASK_ID='Load_time_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T18:40:08.391579+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T18:40:08.391579+00:00'
[2025-07-24T18:50:45.303+0000] {logging_mixin.py:188} INFO - Executing transformation for table: time
[2025-07-24T18:50:45.312+0000] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2025-07-24T18:50:45.316+0000] {sql.py:450} INFO - Running statement: TRUNCATE TABLE time; INSERT INTO time 
        SELECT start_time, extract(hour from start_time), extract(day from start_time), extract(week from start_time),
               extract(month from start_time), extract(year from start_time), extract(DOW from start_time)
        FROM songplays
    , parameters: None
[2025-07-24T18:50:45.333+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/step12345.py", line 232, in load_time_dim_task
    load_table("postgres_local", "time", SqlQueries.time_table_insert)
  File "/opt/airflow/dags/step12345.py", line 177, in load_table
    postgres_hook.run(sql_formatted)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "time_pkey"
DETAIL:  Key (start_time)=(2018-11-14 04:53:36) already exists.

[2025-07-24T18:50:45.348+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_full_etl_dag, task_id=Load_time_dim_table, execution_date=20250724T184008, start_date=20250724T185045, end_date=20250724T185045
[2025-07-24T18:50:45.380+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 115 for task Load_time_dim_table (duplicate key value violates unique constraint "time_pkey"
DETAIL:  Key (start_time)=(2018-11-14 04:53:36) already exists.
; 2166)
[2025-07-24T18:50:45.420+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T18:50:45.453+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
