[2025-07-24T18:28:05.994+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_full_etl_dag.Load_time_dim_table manual__2025-07-24T18:17:21.846820+00:00 [queued]>
[2025-07-24T18:28:06.006+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_full_etl_dag.Load_time_dim_table manual__2025-07-24T18:17:21.846820+00:00 [queued]>
[2025-07-24T18:28:06.007+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2025-07-24T18:28:06.029+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): Load_time_dim_table> on 2025-07-24 18:17:21.846820+00:00
[2025-07-24T18:28:06.041+0000] {standard_task_runner.py:60} INFO - Started process 1764 to run task
[2025-07-24T18:28:06.049+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tunestream_full_etl_dag', 'Load_time_dim_table', 'manual__2025-07-24T18:17:21.846820+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/step12345.py', '--cfg-path', '/tmp/tmprrv5sx27']
[2025-07-24T18:28:06.056+0000] {standard_task_runner.py:88} INFO - Job 93: Subtask Load_time_dim_table
[2025-07-24T18:28:06.113+0000] {task_command.py:423} INFO - Running <TaskInstance: tunestream_full_etl_dag.Load_time_dim_table manual__2025-07-24T18:17:21.846820+00:00 [running]> on host 737498b59352
[2025-07-24T18:28:06.192+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tunestream_full_etl_dag' AIRFLOW_CTX_TASK_ID='Load_time_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T18:17:21.846820+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T18:17:21.846820+00:00'
[2025-07-24T18:28:06.195+0000] {logging_mixin.py:188} INFO - Executing transformation for table: time
[2025-07-24T18:28:06.203+0000] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2025-07-24T18:28:06.209+0000] {sql.py:450} INFO - Running statement: TRUNCATE TABLE time; INSERT INTO time 
        SELECT start_time, extract(hour from start_time), extract(day from start_time), extract(week from start_time),
               extract(month from start_time), extract(year from start_time), extract(dayofweek from start_time)
        FROM songplays
    , parameters: None
[2025-07-24T18:28:06.217+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/step12345.py", line 218, in load_time_dim_task
    load_table("postgres_local", "time", SqlQueries.time_table_insert)
  File "/opt/airflow/dags/step12345.py", line 163, in load_table
    postgres_hook.run(sql_formatted)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidParameterValue: timestamp units "dayofweek" not recognized

[2025-07-24T18:28:06.232+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_full_etl_dag, task_id=Load_time_dim_table, execution_date=20250724T181721, start_date=20250724T182805, end_date=20250724T182806
[2025-07-24T18:28:06.255+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 93 for task Load_time_dim_table (timestamp units "dayofweek" not recognized
; 1764)
[2025-07-24T18:28:06.300+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T18:28:06.326+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
